import { PERMISSIONS } from "./permissions";

export const ACCESS_PERMISSIONS = [
  { key: PERMISSIONS.DASHBOARD_VIEW, description: "Visualizar painel administrativo" },
  { key: PERMISSIONS.USERS_VIEW, description: "Visualizar usuarios" },
  { key: PERMISSIONS.USERS_MANAGE, description: "Criar e editar usuarios" },
  { key: PERMISSIONS.SALES_VIEW, description: "Visualizar historico completo de vendas" },
  { key: PERMISSIONS.COUPONS_VIEW, description: "Visualizar cupons" },
  { key: PERMISSIONS.COUPONS_MANAGE, description: "Criar e editar cupons" },
  { key: PERMISSIONS.SERVICES_VIEW, description: "Visualizar servicos por tempo" },
  { key: PERMISSIONS.PAYMENTS_VIEW, description: "Visualizar auditoria de pagamentos" },
  { key: PERMISSIONS.ACCOUNTS_VIEW, description: "Visualizar contas a pagar" },
  { key: PERMISSIONS.ACCOUNTS_MANAGE, description: "Criar e editar contas a pagar" },
  { key: PERMISSIONS.REPORTS_VIEW, description: "Visualizar relatorios financeiros" },
  { key: PERMISSIONS.FISCAL_VIEW, description: "Visualizar documentos fiscais e XML" },
  { key: PERMISSIONS.SERVICE_FISCAL_VIEW, description: "Visualizar apuracao fiscal de servicos" },
  { key: PERMISSIONS.SERVICE_FISCAL_MANAGE, description: "Registrar apuracao fiscal de servicos" },
  { key: PERMISSIONS.CATEGORIES_VIEW, description: "Visualizar categorias" },
  { key: PERMISSIONS.CATEGORIES_MANAGE, description: "Criar e editar categorias" },
  { key: PERMISSIONS.SUPPLIERS_VIEW, description: "Visualizar fornecedores" },
  { key: PERMISSIONS.SUPPLIERS_MANAGE, description: "Criar e editar fornecedores" },
  { key: PERMISSIONS.CUSTOMERS_VIEW, description: "Visualizar clientes" },
  { key: PERMISSIONS.CUSTOMERS_MANAGE, description: "Criar e editar clientes" },
  { key: PERMISSIONS.PRODUCTS_VIEW, description: "Visualizar produtos" },
  { key: PERMISSIONS.PRODUCTS_MANAGE, description: "Criar e editar produtos" },
  { key: PERMISSIONS.STOCK_VIEW, description: "Visualizar movimentacoes de estoque" },
  { key: PERMISSIONS.STOCK_MANAGE, description: "Registrar movimentacoes de estoque" },
  { key: PERMISSIONS.CASH_VIEW, description: "Visualizar sessoes de caixa" },
  { key: PERMISSIONS.CASH_MANAGE, description: "Abrir e fechar caixa, registrar sangria e suprimento" },
  { key: PERMISSIONS.PDV_VIEW, description: "Visualizar PDV" },
  { key: PERMISSIONS.PDV_MANAGE, description: "Registrar vendas no PDV" },
  { key: PERMISSIONS.PDV_CANCEL, description: "Cancelar vendas no PDV" },
  { key: PERMISSIONS.SUPPORT_VIEW, description: "Visualizar suporte" },
  { key: PERMISSIONS.SUPPORT_MANAGE, description: "Criar e atualizar tickets de suporte" },
  { key: PERMISSIONS.MODULES_VIEW, description: "Visualizar biblioteca de modulos" },
  { key: PERMISSIONS.GOALS_VIEW, description: "Visualizar metas" },
  { key: PERMISSIONS.GOALS_MANAGE, description: "Criar e editar metas" },
  { key: PERMISSIONS.CUSTOMIZATION_VIEW, description: "Visualizar configuracoes" },
  { key: PERMISSIONS.CUSTOMIZATION_MANAGE, description: "Editar configuracoes do sistema" },
  { key: PERMISSIONS.TV_APP_VIEW, description: "Visualizar pagina do app da TV" },
] as const;

export const ACCESS_ROLE_PERMISSION_KEYS = {
  administrador: ACCESS_PERMISSIONS.map((permission) => permission.key),
  financeiro: [
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.ACCOUNTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.FISCAL_VIEW,
    PERMISSIONS.SERVICE_FISCAL_VIEW,
    PERMISSIONS.SERVICE_FISCAL_MANAGE,
  ],
  caixa: [
    PERMISSIONS.PDV_VIEW,
    PERMISSIONS.PDV_MANAGE,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_MANAGE,
  ],
  gerente: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.COUPONS_VIEW,
    PERMISSIONS.COUPONS_MANAGE,
    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.ACCOUNTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.FISCAL_VIEW,
    PERMISSIONS.SERVICE_FISCAL_VIEW,
    PERMISSIONS.SERVICE_FISCAL_MANAGE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_MANAGE,
    PERMISSIONS.PDV_VIEW,
    PERMISSIONS.PDV_MANAGE,
    PERMISSIONS.PDV_CANCEL,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.MODULES_VIEW,
    PERMISSIONS.GOALS_VIEW,
    PERMISSIONS.GOALS_MANAGE,
    PERMISSIONS.CUSTOMIZATION_VIEW,
    PERMISSIONS.CUSTOMIZATION_MANAGE,
    PERMISSIONS.TV_APP_VIEW,
  ],
  operador: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.COUPONS_VIEW,
    PERMISSIONS.COUPONS_MANAGE,
    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PDV_VIEW,
    PERMISSIONS.PDV_MANAGE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.STOCK_MANAGE,
    PERMISSIONS.CASH_VIEW,
    PERMISSIONS.CASH_MANAGE,
  ],
} as const;

export const ACCESS_ROLES = [
  {
    slug: "administrador",
    name: "Administrador",
    description: "Controle total da plataforma",
  },
  {
    slug: "financeiro",
    name: "Financeiro",
    description: "Acesso restrito a pagamentos, contas, relatorios e fiscal",
  },
  {
    slug: "caixa",
    name: "Caixa",
    description: "Acesso restrito ao PDV e operacao de caixa",
  },
  {
    slug: "gerente",
    name: "Gerente",
    description: "Gestao operacional e acompanhamento de indicadores",
  },
  {
    slug: "operador",
    name: "Operador",
    description: "Operacao diaria de cadastro e estoque",
  },
] as const;

export const ACCESS_ROLE_SLUGS_TO_SYNC = ACCESS_ROLES.map((role) => role.slug);
